// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// fcalc_np
double fcalc_np(double& c_i, NumericVector& c_j);
RcppExport SEXP _crosstalkr_fcalc_np(SEXP c_iSEXP, SEXP c_jSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double& >::type c_i(c_iSEXP);
    Rcpp::traits::input_parameter< NumericVector& >::type c_j(c_jSEXP);
    rcpp_result_gen = Rcpp::wrap(fcalc_np(c_i, c_j));
    return rcpp_result_gen;
END_RCPP
}
// fcalc_np_all
NumericVector fcalc_np_all(List& neighbors, StringVector& vertices, StringVector& v, NumericVector& exp);
RcppExport SEXP _crosstalkr_fcalc_np_all(SEXP neighborsSEXP, SEXP verticesSEXP, SEXP vSEXP, SEXP expSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List& >::type neighbors(neighborsSEXP);
    Rcpp::traits::input_parameter< StringVector& >::type vertices(verticesSEXP);
    Rcpp::traits::input_parameter< StringVector& >::type v(vSEXP);
    Rcpp::traits::input_parameter< NumericVector& >::type exp(expSEXP);
    rcpp_result_gen = Rcpp::wrap(fcalc_np_all(neighbors, vertices, v, exp));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_crosstalkr_fcalc_np", (DL_FUNC) &_crosstalkr_fcalc_np, 2},
    {"_crosstalkr_fcalc_np_all", (DL_FUNC) &_crosstalkr_fcalc_np_all, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_crosstalkr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
