// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// cpp_RWR
Rcpp::List cpp_RWR(arma::sp_mat w, CharacterVector rownames, CharacterVector seed_proteins, int tmax, double gamma, double eps);
RcppExport SEXP _crosstalkr_cpp_RWR(SEXP wSEXP, SEXP rownamesSEXP, SEXP seed_proteinsSEXP, SEXP tmaxSEXP, SEXP gammaSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::sp_mat >::type w(wSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type rownames(rownamesSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type seed_proteins(seed_proteinsSEXP);
    Rcpp::traits::input_parameter< int >::type tmax(tmaxSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_RWR(w, rownames, seed_proteins, tmax, gamma, eps));
    return rcpp_result_gen;
END_RCPP
}
// timesTwo
NumericVector timesTwo(NumericVector x);
RcppExport SEXP _crosstalkr_timesTwo(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(timesTwo(x));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_crosstalkr_cpp_RWR", (DL_FUNC) &_crosstalkr_cpp_RWR, 6},
    {"_crosstalkr_timesTwo", (DL_FUNC) &_crosstalkr_timesTwo, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_crosstalkr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
