# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_RWR <- function(w, rownames, seed_proteins, tmax = 1000L, gamma = 0.6, eps = 1e-10) {
    .Call(`_crosstalkr_cpp_RWR`, w, rownames, seed_proteins, tmax, gamma, eps)
}

timesTwo <- function(x) {
    .Call(`_crosstalkr_timesTwo`, x)
}

